# Generated by Django 4.1.5 on 2023-01-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follwers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follwers', models.CharField(max_length=2000)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
