# Generated by Django 4.1.5 on 2023-01-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_follwers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follwers',
            new_name='FollowersCount',
        ),
        migrations.RenameField(
            model_name='followerscount',
            old_name='follwers',
            new_name='follower',
        ),
    ]
