# Generated by Django 4.1.3 on 2023-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_follwers_followerscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_bg_img',
            field=models.ImageField(default='userlist-3', upload_to='profile_bg_img'),
        ),
    ]
