# Generated by Django 4.1.3 on 2023-01-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_profile_bg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_bg_img',
        ),
    ]
