# Generated by Django 4.1.3 on 2023-01-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_profile_bg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='social-logo.jpg', upload_to='profile'),
        ),
    ]
