# Generated by Django 4.1.3 on 2023-01-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='timeline-1.jpg', upload_to='profile'),
        ),
    ]
